from django.urls import path
from . import views

urlpatterns = [
    path('admin-home/', views.adminHome, name='adminHome'),
    path('distRegn/', views.distRegn, name='distRegn'),
    path('distRegnInsert/', views.distRegnInsert, name='distRegnInsert'),
    path('distView/', views.distView, name='distView'),
    path('distDelete/<int:id>/', views.distDelete, name='distDelete'),
    path('distEdit/<int:id>/', views.distEdit, name='distEdit'),
    path('locationRegn/', views.locationRegn, name='locationRegn'),
    path('locationInsert/', views.locationInsert, name='locationInsert'),
    path('locationView/', views.locationView, name='locationView'),
    path('filllocation/', views.filllocation, name='filllocation'),
    path('locationDelete/<int:id>/', views.locationDelete, name='locationDelete'),
    path('locationEdit/<int:id>/', views.locationEdit, name='locationEdit'),
    path('disabilityRegn/', views.disabilityRegn, name='disabilityRegn'),
    path('disabilityInsert/', views.disabilityInsert, name='disabilityInsert'),
    path('disabilityView/', views.disabilityView, name='disabilityView'),
    path('disabilityDelete/<int:id>/', views.disabilityDelete, name='disabilityDelete'),
    path('disabilityEdit/<int:id>/', views.disabilityEdit, name='disabilityEdit'),
    path('accessibilityRegn/', views.accessibilityRegn, name='accessibilityRegn'),
    path('accessibilityInsert/', views.accessibilityInsert, name='accessibilityInsert'),
    path('accessibilityView/', views.accessibilityView, name='accessibilityView'),
    path('accessibilityDelete/<int:id>/', views.accessibilityDelete, name='accessibilityDelete'),
    path('accessibilityEdit/<int:id>/', views.accessibilityEdit, name='accessibilityEdit'),
    path('operator-verification/', views.operatorVerification, name='operatorVerification'),
    path('license-view/<int:id>/', views.licenseView, name='licenseView'),
    path('operator-approve/<int:id>/', views.operatorApprove, name='operatorApprove'),
    path('operator-reject/<int:id>/', views.operatorReject, name='operatorReject'),
    path('operators-view/', views.operatorsView, name='operatorsView'),
    path('operator-block/<int:id>/', views.operatorBlock, name='operatorBlock'),
    path('operator-unblock/<int:id>/', views.operatorUnblock, name='operatorUnblock'),
    path('operator-profile/<int:id>/', views.operatorProfile, name='operatorProfile'),
    path('travellers-view/', views.travellersView, name='travellersView'),
    path('traveller-profile/<int:id>/', views.travellerProfile, name='travellerProfile'),
    path('traveller-block/<int:id>/', views.travellerBlock, name='travellerBlock'),
    path('traveller-unblock/<int:id>/', views.travellerUnblock, name='travellerUnblock'),
    path('bookings-view/', views.bookingsView, name='bookingsView'),
    path('reports/', views.admin_datewise_report, name='admin_datewise_report'),
    path('reports/export/', views.admin_bookings_export, name='admin_bookings_export'),
]