# Generated by Django 5.2.10 on 2026-01-15 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminApp', '0004_rename_district_id_location_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('operator_id', models.AutoField(primary_key=True, serialize=False)),
                ('operator_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100)),
                ('status', models.CharField(default='requested', max_length=20)),
                ('license', models.ImageField(upload_to='operator_licenses/')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.district')),
            ],
        ),
    ]
