# Generated by Django 5.2.10 on 2026-01-08 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminApp', '0001_initial'),
        ('guestApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('contact_no', models.IntegerField()),
                ('verification_status', models.CharField(default='PENDING', max_length=10)),
                ('subscription_plan', models.CharField(default='FREE', max_length=10)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminApp.location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='guestApp.login')),
            ],
        ),
    ]
