# Generated by Django 5.2.10 on 2026-01-13 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminApp', '0002_accessibility_disability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('operator_id', models.AutoField(primary_key=True, serialize=False)),
                ('operator_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('license', models.ImageField(upload_to='licenses/')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.location')),
            ],
        ),
    ]
