# Generated by Django 5.2.10 on 2026-01-15 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0005_remove_accessibility_id_remove_disability_id_and_more'),
        ('operatorApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminApp.district'),
        ),
    ]
