# Generated by Django 5.2.10 on 2026-01-13 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operatorApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operator',
            old_name='location_id',
            new_name='location',
        ),
    ]
