# Generated by Django 5.2.10 on 2026-01-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operatorApp', '0002_alter_operator_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='license',
            field=models.FileField(upload_to='operator_licenses/'),
        ),
    ]
