# Generated by Django 5.2.10 on 2026-01-29 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operatorApp', '0002_alter_tour_duration_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='touraccessibility',
            name='extra_cost_per_person',
            field=models.FloatField(default=0.0),
        ),
    ]
