# Generated by Django 5.2.10 on 2026-01-29 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operatorApp', '0003_touraccessibility_extra_cost_per_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='touraccessibility',
            old_name='extra_cost_per_person',
            new_name='extra_cost_per_acc',
        ),
    ]
