# Generated by Django 5.2.10 on 2026-01-18 08:03

import django.db.models.deletion
import operatorApp.views
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestApp', '0001_initial'),
        ('operatorApp', '0003_alter_operator_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='login',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='guestApp.login'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operator',
            name='license',
            field=models.FileField(upload_to='operator_licenses/', validators=[operatorApp.views.validate_pdf]),
        ),
    ]
