# Generated by Django 5.2.10 on 2026-01-19 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0005_remove_accessibility_id_remove_disability_id_and_more'),
        ('operatorApp', '0004_operator_login_alter_operator_license'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('tour_id', models.AutoField(primary_key=True, serialize=False)),
                ('tour_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('duration_days', models.IntegerField()),
                ('max_persons', models.IntegerField()),
                ('status', models.CharField(default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminApp.location')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operatorApp.operator')),
            ],
        ),
        migrations.CreateModel(
            name='TourAccessibility',
            fields=[
                ('tour_acc_id', models.AutoField(primary_key=True, serialize=False)),
                ('accessibility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.accessibility')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operatorApp.tour')),
            ],
        ),
        migrations.CreateModel(
            name='TourImages',
            fields=[
                ('tour_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='tour_images/')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operatorApp.tour')),
            ],
        ),
    ]
