# Generated by Django 5.2.10 on 2026-01-20 05:54

import operatorApp.views
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operatorApp', '0005_tour_touraccessibility_tourimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='tour_itinerary',
            field=models.FileField(null=True, upload_to='tour_itineraries/', validators=[operatorApp.views.validate_pdf]),
        ),
    ]
