# Generated by Django 5.2.10 on 2026-01-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessibility',
            fields=[
                ('accessibility_id', models.AutoField(primary_key=True, serialize=False)),
                ('accessibility_feature', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disability',
            fields=[
                ('disability_id', models.AutoField(primary_key=True, serialize=False)),
                ('disability_type', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
