# Generated by Django 5.2.10 on 2026-01-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0002_accessibility_disability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessibility',
            name='accessibility_id',
        ),
        migrations.RemoveField(
            model_name='disability',
            name='disability_id',
        ),
        migrations.RemoveField(
            model_name='district',
            name='district_id',
        ),
        migrations.RemoveField(
            model_name='location',
            name='location_id',
        ),
        migrations.AddField(
            model_name='accessibility',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='disability',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='district',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='location',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
