# Generated by Django 5.2.10 on 2026-01-15 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0003_remove_accessibility_accessibility_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='district_id',
            new_name='district',
        ),
    ]
