# Generated by Django 5.2.10 on 2026-01-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0004_rename_district_id_location_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessibility',
            name='id',
        ),
        migrations.RemoveField(
            model_name='disability',
            name='id',
        ),
        migrations.RemoveField(
            model_name='district',
            name='id',
        ),
        migrations.RemoveField(
            model_name='location',
            name='id',
        ),
        migrations.AddField(
            model_name='accessibility',
            name='accessibility_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='disability',
            name='disability_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='district',
            name='district_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='location',
            name='location_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
