# Generated by Django 5.2.10 on 2026-01-14 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminApp', '0002_accessibility_disability'),
        ('guestApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravellerProfile',
            fields=[
                ('traveller_id', models.AutoField(primary_key=True, serialize=False)),
                ('traveller_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('disability', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminApp.disability')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestApp.login')),
            ],
        ),
    ]
