# Generated by Django 5.2.10 on 2026-01-29 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminApp', '0005_remove_accessibility_id_remove_disability_id_and_more'),
        ('guestApp', '0003_travellerprofile'),
        ('operatorApp', '0004_rename_extra_cost_per_person_touraccessibility_extra_cost_per_acc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('tour_date', models.DateField()),
                ('total_persons', models.IntegerField()),
                ('persons_needing_accessibility', models.IntegerField(default=0, null=True)),
                ('caregiver_gender_preference', models.CharField(blank=True, max_length=10, null=True)),
                ('base_amount', models.FloatField()),
                ('accessibility_amount', models.FloatField(default=0.0)),
                ('total_amount', models.FloatField()),
                ('booking_status', models.CharField(default='pending', max_length=20)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operatorApp.tour')),
                ('traveller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestApp.travellerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BookingAccessibility',
            fields=[
                ('booking_acc_id', models.AutoField(primary_key=True, serialize=False)),
                ('accessibility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.accessibility')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.booking')),
            ],
        ),
    ]
