# Generated by Django 5.2.10 on 2026-02-10 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0003_chat_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
