# Generated by Django 5.2.10 on 2026-02-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0004_remove_message_chat_delete_chat_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='commission_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
