# Generated by Django 5.2.10 on 2026-02-16 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestApp', '0003_travellerprofile'),
        ('operatorApp', '0004_rename_extra_cost_per_person_touraccessibility_extra_cost_per_acc'),
        ('userApp', '0005_booking_commission_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userApp.booking')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operatorApp.tour')),
                ('traveller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestApp.travellerprofile')),
            ],
        ),
    ]
