# Generated by Django 5.2.10 on 2026-01-20 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0005_remove_accessibility_id_remove_disability_id_and_more'),
        ('guestApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('operator_id', models.AutoField(primary_key=True, serialize=False)),
                ('operator_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100)),
                ('status', models.CharField(default='requested', max_length=20)),
                ('license', models.FileField(upload_to='operator_licenses/')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminApp.district')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestApp.login')),
            ],
        ),
    ]
