# Generated by Django 5.2.10 on 2026-02-16 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0005_remove_accessibility_id_remove_disability_id_and_more'),
        ('guestApp', '0003_travellerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravellerAccessibility',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('accessibility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.accessibility')),
                ('traveller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestApp.travellerprofile')),
            ],
            options={
                'unique_together': {('traveller', 'accessibility')},
            },
        ),
    ]
